version: '3.8'

services:
  mysql-eastern:
    image: mysql:8.0
    container_name: mysql_eastern_repro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: olake_test
      TZ: US/Eastern
    command: >
      --default-authentication-plugin=mysql_native_password
      --server-id=1
      --default-time-zone="US/Eastern"
      --log-bin=mysql-bin
      --binlog-format=ROW
      --binlog-row-image=FULL
      --binlog-row-metadata=FULL
      
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
    ports:
      - "3306:3306"